In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


n_samples = 100


independent_features = np.random.randn(n_samples, 6)  
columns_independent = [f'X{i+1}' for i in range(6)]


coefficients = np.random.rand(6, 4)  
dependent_features = np.dot(independent_features, coefficients) + np.random.randn(n_samples, 4) * 0.1
columns_dependent = [f'X{i+7}' for i in range(4)]


data = pd.DataFrame(np.hstack([independent_features, dependent_features]),
                    columns=columns_independent + columns_dependent)



In [29]:
data

X1        X2        X3        X4        X5        X6        X7  \
0   0.761639 -0.499694  1.020868  0.381831 -2.581919 -1.444995 -0.219882   
1  -1.343341 -0.450861 -0.726560 -1.062360 -0.203591  0.349364 -1.463656   
2   1.114873 -1.294518  0.158496 -0.260306 -0.120052  0.128599 -0.262510   
3   1.817617  0.576066 -0.683581 -0.702884  0.204420 -0.408782 -0.596278   
4   0.648293  0.672837  0.746561 -0.441718 -0.457317  1.407933  0.385791   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.345908 -0.180051  0.788457  0.097083  1.898353  0.326192  1.805594   
96 -0.537023  0.389290  0.075972  0.465367 -1.721163 -0.052228 -0.620791   
97 -0.615412  0.383349 -0.899938 -0.812470 -0.759502  0.512642 -1.482104   
98 -1.192197  0.607324 -0.106867  0.503398 -0.350444 -0.336421 -0.071592   
99  0.684412 -0.884485  0.385297 -2.037330 -0.436349  1.841721 -1.011098   

          X8        X9       X10  
0  -2.454244 -0.851969 -1.157256  
1  -1.372279 -2.172736 -1.925698  
2  -0.609315  0.171712 -0.424206  
3   0.477790  0.287232  0.018521  
4   1.207996  1.537877  1.353612  
..       ...       ...       ...  
95  1.953788  1.970884  1.606354  
96 -1.070061 -0.667331 -0.338221  
97 -0.926048 -1.705467 -1.361604  
98 -0.264613 -0.602565 -0.063739  
99 -0.283377  0.015434 -0.922800  

[100 rows x 10 columns]

In [30]:
X_Transpose = np.array(data)
X_bar_Transpose = X_Transpose - np.mean(X_Transpose,axis = 0)
X_bar_Transpose


array([[ 6.07108158e-01, -4.52219812e-01,  1.14336201e+00,
         5.22068595e-01, -2.47059574e+00, -1.39328332e+00,
         2.04745011e-02, -2.25022204e+00, -6.55807332e-01,
        -9.57041236e-01],
       [-1.49787171e+00, -4.03386378e-01, -6.04065993e-01,
        -9.22122547e-01, -9.22677641e-02,  4.01075301e-01,
        -1.22329934e+00, -1.16825700e+00, -1.97657480e+00,
        -1.72548338e+00],
       [ 9.60342617e-01, -1.24704356e+00,  2.80990229e-01,
        -1.20068506e-01, -8.72861375e-03,  1.80309973e-01,
        -2.21537104e-02, -4.05292811e-01,  3.67872828e-01,
        -2.23991850e-01],
       [ 1.66308695e+00,  6.23540264e-01, -5.61086802e-01,
        -5.62646563e-01,  3.15743075e-01, -3.57070589e-01,
        -3.55921623e-01,  6.81812458e-01,  4.83393615e-01,
         2.18735141e-01],
       [ 4.93762887e-01,  7.20311664e-01,  8.69055733e-01,
        -3.01480417e-01, -3.45993647e-01,  1.45964408e+00,
         6.26147296e-01,  1.41201833e+00,  1.73403772e+00,
         1.

In [31]:
N_Train =data.shape[0]
X_bar = X_bar_Transpose.T
Sigma = (1/N_Train)*np.matmul(X_bar,X_bar_Transpose)

In [32]:
Sigma

array([[ 9.34671919e-01,  2.21018700e-02,  1.32664689e-01,
         1.06873602e-01, -2.02864239e-02, -9.72975141e-04,
         2.09955241e-01,  4.06669014e-01,  7.52272273e-01,
         5.24311821e-01],
       [ 2.21018700e-02,  8.95655111e-01,  4.48246869e-02,
         1.25381472e-01, -1.86259581e-02, -2.82839287e-02,
         1.40996081e-01,  6.50629569e-01,  4.08438844e-01,
         6.66341031e-01],
       [ 1.32664689e-01,  4.48246869e-02,  9.60396399e-01,
         2.48854411e-01, -8.03137198e-03, -3.68227172e-02,
         9.36877735e-01,  4.59022291e-01,  1.08533013e+00,
         6.86846904e-01],
       [ 1.06873602e-01,  1.25381472e-01,  2.48854411e-01,
         1.28404673e+00,  6.25444419e-02, -2.17608579e-01,
         9.70417582e-01,  6.37546735e-01,  1.10015850e+00,
         1.22945945e+00],
       [-2.02864239e-02, -1.86259581e-02, -8.03137198e-03,
         6.25444419e-02,  9.27447909e-01, -3.74223710e-02,
         4.88168538e-01,  7.21024036e-01,  4.82502997e-01,
         4.

In [33]:
factorized_sigma = np.linalg.svd(Sigma)
factorized_sigma

SVDResult(U=array([[-0.12162716,  0.07170743,  0.4435726 ,  0.17242264, -0.74922009,
        -0.20606594, -0.25696461, -0.12548609,  0.01172724, -0.26051804],
       [-0.11421339,  0.28642024, -0.32919448,  0.43594296, -0.08187484,
         0.61103231, -0.06610086, -0.0189793 , -0.33732254, -0.32851707],
       [-0.19598285, -0.31555956,  0.39315083, -0.19889112,  0.1837285 ,
         0.49991586,  0.02150706,  0.10372547,  0.43050231, -0.43319955],
       [-0.25138523, -0.38617051, -0.29940233,  0.38554565,  0.18046717,
        -0.47484413,  0.1751331 , -0.16752056,  0.08174545, -0.47531903],
       [-0.11978197,  0.14059317, -0.43190948, -0.6639888 , -0.23822786,
        -0.13626906, -0.03268541,  0.30266941, -0.0822987 , -0.40458245],
       [-0.05090462,  0.57343868,  0.37904088, -0.06764894,  0.52305208,
        -0.25978812, -0.15009648, -0.10562548, -0.19739902, -0.32650117],
       [-0.37924938, -0.36896824, -0.03738835, -0.25104257,  0.11842629,
         0.07974395, -0.54828786,

In [34]:
Q_Transpose = factorized_sigma[0]
Q = Q_Transpose.T
z = np.matmul(Q,X_bar)
z

array([[ 1.73215782e+00,  3.44298109e+00,  8.01181811e-02,
        -5.54881778e-01, -2.79901013e+00, -5.11314604e+00,
        -1.66874280e+00, -2.59883038e+00,  1.82523169e+00,
        -1.91257493e+00,  6.54059665e+00, -5.75252230e-01,
        -3.18870478e-01, -2.84912540e+00,  3.39175014e+00,
         3.53958195e+00,  6.24205040e+00,  2.18249225e+00,
         1.12422142e+00,  2.42301473e+00,  5.46920598e+00,
        -4.01089948e+00, -1.08970705e+00,  1.87148063e+00,
        -7.61876489e-01, -2.64206179e+00,  4.44330548e+00,
        -4.95119330e+00, -1.22464758e+00, -1.90323125e+00,
         9.20962857e-01,  1.84012121e+00,  3.15556676e+00,
        -4.19073702e+00,  3.70614677e+00,  4.26373572e+00,
        -2.10475273e+00,  2.29731627e+00, -9.65311657e-02,
         3.74327430e+00, -3.86348328e-01, -1.98928139e+00,
        -2.86752014e+00, -7.08071464e-01, -4.41762412e+00,
         2.44125804e+00,  1.78010482e+00,  2.78194306e+00,
         2.41952784e+00,  1.36999158e+00, -5.37927571e+0

In [35]:
column_names = [f'Z{i+1}' for i in range(z.shape[0])]
projected_training_data = pd.DataFrame(data=z.T, columns=column_names)
projected_training_data

Z1        Z2        Z3        Z4        Z5        Z6        Z7  \
0   1.732158 -2.806091  1.586302  1.680861 -0.105202  0.569615 -0.201349   
1   3.442981  0.362247 -0.432111 -0.519132  1.036234  0.105925  0.097955   
2   0.080118 -0.427136  1.253188 -0.507451 -0.505965 -0.811243  0.039192   
3  -0.554882  0.946287  0.203096  0.302630 -1.876646  0.071535  0.004193   
4  -2.799010  1.353464  1.169055  0.213450  0.504437  0.570747 -0.037677   
..       ...       ...       ...       ...       ...       ...       ...   
95 -4.238126  0.368537 -0.357440 -1.909557 -0.122632 -0.024125 -0.188045   
96  0.856038 -0.652843  0.207546  1.526985  1.059756  0.363784  0.113675   
97  2.578105  0.872309 -0.227836  0.527475  0.634974  0.263911  0.049161   
98  0.078456 -0.410896 -1.120060  0.497912  1.048842  0.478819  0.058603   
99  0.925259  1.554072  2.294391 -1.010711  0.321897  0.098874  0.149424   

          Z8        Z9       Z10  
0  -0.059531  0.109332 -0.013862  
1   0.008619  0.010710 -0.001600  
2   0.102984  0.097760 -0.030443  
3  -0.075021 -0.123214  0.048739  
4  -0.023870 -0.042118  0.060370  
..       ...       ...       ...  
95  0.006524  0.017272  0.027920  
96 -0.016916  0.012057  0.000273  
97 -0.175249 -0.130830 -0.051749  
98 -0.020481  0.022242  0.000134  
99 -0.003217 -0.032764  0.048198  

[100 rows x 10 columns]

In [40]:

Eigen_Values = factorized_sigma[1]
TOT = np.sum(Eigen_Values)
var_sum = 0 
Predefined_variance_percentage = 0.9
for i in range(Eigen_Values.shape[0]):
    var_sum += Eigen_Values[i]
    if (var_sum / TOT) > Predefined_variance_percentage:
        break
projected_dim_reduce_data = projected_training_data.iloc[:, :i]

projected_dim_reduce_data

Z1        Z2        Z3        Z4
0   1.732158 -2.806091  1.586302  1.680861
1   3.442981  0.362247 -0.432111 -0.519132
2   0.080118 -0.427136  1.253188 -0.507451
3  -0.554882  0.946287  0.203096  0.302630
4  -2.799010  1.353464  1.169055  0.213450
..       ...       ...       ...       ...
95 -4.238126  0.368537 -0.357440 -1.909557
96  0.856038 -0.652843  0.207546  1.526985
97  2.578105  0.872309 -0.227836  0.527475
98  0.078456 -0.410896 -1.120060  0.497912
99  0.925259  1.554072  2.294391 -1.010711

[100 rows x 4 columns]